/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Controladores.characterController;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 * Tela visual para a criação de personagem
 *
 * @author Otávio
 */
public class createCharacter extends javax.swing.JPanel {

    /**
     * Creates new form createCharacter
     */
    public createCharacter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escolhaClasse = new javax.swing.ButtonGroup();
        criarPersonagem = new javax.swing.JButton();
        jogadorNome = new javax.swing.JTextField();
        labelName = new javax.swing.JLabel();
        guerreiro = new javax.swing.JRadioButton();
        arqueiro = new javax.swing.JRadioButton();
        mago = new javax.swing.JRadioButton();
        classLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        criarPersonagem.setBackground(new java.awt.Color(0, 0, 0));
        criarPersonagem.setForeground(new java.awt.Color(255, 255, 255));
        criarPersonagem.setText("Começar");
        criarPersonagem.setFocusPainted(false);
        criarPersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarPersonagemActionPerformed(evt);
            }
        });

        jogadorNome.setBackground(new java.awt.Color(0, 0, 0));
        jogadorNome.setForeground(new java.awt.Color(255, 255, 255));
        jogadorNome.setCaretColor(new java.awt.Color(255, 255, 255));
        jogadorNome.setSelectionColor(new java.awt.Color(153, 153, 153));
        jogadorNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogadorNomeActionPerformed(evt);
            }
        });

        labelName.setForeground(new java.awt.Color(255, 255, 255));
        labelName.setText("Nome do Jogador");

        guerreiro.setBackground(new java.awt.Color(0, 0, 0));
        escolhaClasse.add(guerreiro);
        guerreiro.setForeground(new java.awt.Color(255, 255, 255));
        guerreiro.setSelected(true);
        guerreiro.setText("Guerreiro");
        guerreiro.setFocusPainted(false);
        guerreiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guerreiroActionPerformed(evt);
            }
        });

        arqueiro.setBackground(new java.awt.Color(0, 0, 0));
        escolhaClasse.add(arqueiro);
        arqueiro.setForeground(new java.awt.Color(255, 255, 255));
        arqueiro.setText("Arqueiro");
        arqueiro.setFocusPainted(false);
        arqueiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arqueiroActionPerformed(evt);
            }
        });

        mago.setBackground(new java.awt.Color(0, 0, 0));
        escolhaClasse.add(mago);
        mago.setForeground(new java.awt.Color(255, 255, 255));
        mago.setText("Mago");
        mago.setFocusPainted(false);
        mago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                magoActionPerformed(evt);
            }
        });

        classLabel.setForeground(new java.awt.Color(255, 255, 255));
        classLabel.setText("Escolha uma classe");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jogadorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(criarPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(classLabel)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mago)
                                .addComponent(guerreiro, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(arqueiro)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jogadorNome)
                    .addComponent(labelName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(classLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guerreiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(arqueiro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mago, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(criarPersonagem)
                .addGap(92, 92, 92))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void criarPersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarPersonagemActionPerformed
        characterController.criaPersonagem(jogadorNome.getText(),capturaClasseSelecionada(escolhaClasse));
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        waitingScreen avancar = new waitingScreen();
        frame.setContentPane(avancar);
        frame.validate();
    }//GEN-LAST:event_criarPersonagemActionPerformed

    private void jogadorNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogadorNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jogadorNomeActionPerformed

    private void guerreiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guerreiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guerreiroActionPerformed

    private void arqueiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arqueiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arqueiroActionPerformed

    private void magoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_magoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_magoActionPerformed

    public int capturaClasseSelecionada(javax.swing.ButtonGroup buttonGroup) {
        int index = 0;
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return index;
            }
            index++;
        }
        return index;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton arqueiro;
    private javax.swing.JLabel classLabel;
    private javax.swing.JButton criarPersonagem;
    private javax.swing.ButtonGroup escolhaClasse;
    private javax.swing.JRadioButton guerreiro;
    private javax.swing.JTextField jogadorNome;
    private javax.swing.JLabel labelName;
    private javax.swing.JRadioButton mago;
    // End of variables declaration//GEN-END:variables
}
