/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

import static java.lang.System.exit;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 * Menu inicial do jogo
 *
 * @author Otávio
 */
public class startGame extends javax.swing.JPanel {

    /**
     * Creates new form startGame
     */
    public startGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoInicio = new javax.swing.JButton();
        botaoInstrucoes = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        nomeJogo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        botaoInicio.setBackground(new java.awt.Color(0, 0, 0));
        botaoInicio.setForeground(new java.awt.Color(255, 255, 255));
        botaoInicio.setText("Início");
        botaoInicio.setFocusPainted(false);
        botaoInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInicioActionPerformed(evt);
            }
        });

        botaoInstrucoes.setBackground(new java.awt.Color(0, 0, 0));
        botaoInstrucoes.setForeground(new java.awt.Color(255, 255, 255));
        botaoInstrucoes.setText("Instruções");
        botaoInstrucoes.setFocusPainted(false);
        botaoInstrucoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInstrucoesActionPerformed(evt);
            }
        });

        botaoSair.setBackground(new java.awt.Color(0, 0, 0));
        botaoSair.setForeground(new java.awt.Color(255, 255, 255));
        botaoSair.setText("Sair");
        botaoSair.setFocusPainted(false);
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        nomeJogo.setBackground(new java.awt.Color(255, 255, 255));
        nomeJogo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        nomeJogo.setForeground(new java.awt.Color(255, 255, 255));
        nomeJogo.setText("Adventure Quest");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoInstrucoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(nomeJogo)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(nomeJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoInstrucoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoSair)
                .addContainerGap(108, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInicioActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        createCharacter criar = new createCharacter();
        frame.setContentPane(criar);
        frame.validate();
    }//GEN-LAST:event_botaoInicioActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        exit(0);
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoInstrucoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInstrucoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoInstrucoesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoInicio;
    private javax.swing.JButton botaoInstrucoes;
    private javax.swing.JButton botaoSair;
    private javax.swing.JLabel nomeJogo;
    // End of variables declaration//GEN-END:variables
}
