/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Controladores.itemController;
import Interface.ExternalResources.ButtonColumn;
import RPGGame.Objetos.Buff;
import RPGGame.Objetos.Item;
import RPGGame.gameObjects;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.Iterator;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 * Tela visual para venda de itens dentro da loja
 *
 * @author Otávio
 */
public class vendaScreen extends javax.swing.JPanel {

    /**
     * Creates new form vendaScreen
     */
    public vendaScreen() {
        Action venderItem = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                int modelRow = Integer.valueOf(e.getActionCommand());
                itemController.venderItem(gameObjects.jogador.getItensJogador().get(modelRow));
                minhaFortuna.setText("Você possuí " + gameObjects.jogador.getDinheiro() + " moedas");
                ((DefaultTableModel) itensVendiveis.getModel()).removeRow(modelRow);
                JOptionPane.showMessageDialog(null, "Você vendeu o item com sucesso!");
            }
        };
        initComponents();
        DefaultTableModel tableModel = (DefaultTableModel) itensVendiveis.getModel();
        Iterator<Item> iterator = gameObjects.jogador.iterator();
        while (iterator.hasNext()) {
            Item i = iterator.next();
            String efeito = "";
            if (i.getBuff() != null) {
                for (Buff b : i.getBuff()) {
                    efeito = "+" + b.getBuff() + " " + b.getTipoBuff().getTipo() + " ";
                }
            }
            tableModel.addRow(new Object[]{i.getNomeItem(), i.getDescricaoItem(), i.getTipo(), i.getPrecoVenda(), efeito, "Vender"});
        }
        ButtonColumn buttonColumn = new ButtonColumn(itensVendiveis, venderItem, 5);
        buttonColumn.setMnemonic(KeyEvent.VK_D);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        descricao = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        itensVendiveis = new javax.swing.JTable();
        voltarCidade = new javax.swing.JButton();
        minhaFortuna = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        descricao.setBackground(new java.awt.Color(0, 0, 0));
        descricao.setColumns(20);
        descricao.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        descricao.setForeground(new java.awt.Color(255, 255, 255));
        descricao.setLineWrap(true);
        descricao.setRows(2);
        descricao.setText("\"O homem vê que você tem alguns itens valiosos em seu inventário e lhe oferece uma boa quantia de ouro em troca de alguns deles.\"");
        jScrollPane2.setViewportView(descricao);

        itensVendiveis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Item", "Descrição", "Tipo", "Preço de Venda", "Efeito", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        itensVendiveis.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(itensVendiveis);

        voltarCidade.setBackground(new java.awt.Color(0, 0, 0));
        voltarCidade.setForeground(new java.awt.Color(255, 255, 255));
        voltarCidade.setText("Voltar para a Loja");
        voltarCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarCidadeActionPerformed(evt);
            }
        });

        minhaFortuna.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        minhaFortuna.setForeground(new java.awt.Color(255, 255, 255));
        minhaFortuna.setText("Você possuí " + gameObjects.jogador.getDinheiro() + " moedas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(minhaFortuna, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voltarCidade)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltarCidade)
                    .addComponent(minhaFortuna))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void voltarCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarCidadeActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        lojaScreen lojaScreen = new lojaScreen();
        frame.setContentPane(lojaScreen);
        frame.validate();
    }//GEN-LAST:event_voltarCidadeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descricao;
    private javax.swing.JTable itensVendiveis;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel minhaFortuna;
    private javax.swing.JButton voltarCidade;
    // End of variables declaration//GEN-END:variables
}
